"""
Profile Product Surface Module
"""

__all__ = ["PROFILEPRODSURFACE", "PPSURFACE", "PPSURF", "PPSU"]


def PROFILEPRODSURFACE(a, b):
    return PROFILEPRODSURFACE([a, b])


PPSURFACE = PROFILEPRODSURFACE
PPSURF = PROFILEPRODSURFACE
PPSU = PROFILEPRODSURFACE
